/*
 * Essentials of AI - Secure Exam Question Bank
 * 120 questions across Day 1-11 (easy to medium).
 * type: "single" (one correct), "multi" (more than one correct), "tf" (true/false)
 * answer: index (single/tf) or array of indices (multi) into options[]
 * time : per-question timer in seconds
 * hint : a fun real-life example (shown on the 💡 Hint button)
 * key  : a short keyword clue unlocked by the 🧩 Super Hint puzzle
 */
const QUESTIONS = [
  // ---------------- Day 1: Python Foundations ----------------
  { id:1, day:1, topic:"Python Foundations", type:"single", diff:"easy", time:30,
    q:"Before running, CPython usually compiles your Python source code into what?",
    options:["Machine assembly","Bytecode","HTML","SQL"], answer:1,
    hint:"Like translating a recipe into a kitchen's shorthand before cooking — Python first turns code into bytecode for its 'kitchen' (the VM). 🍳",
    key:"a compiled intermediate step → byte____" },
  { id:2, day:1, topic:"Python Foundations", type:"tf", diff:"easy", time:20,
    q:"In Python, even integers are objects.", options:["True","False"], answer:0,
    hint:"Everything in Python is a 'thing' you can inspect — even the number 5 has an identity, like every product has a barcode. 🏷️",
    key:"everything in Python is an object" },
  { id:3, day:1, topic:"Python Foundations", type:"single", diff:"easy", time:30,
    q:"A Python variable is best understood as:",
    options:["A fixed memory box","A label/reference pointing to an object","Only a number container","A compiled file"], answer:1,
    hint:"A variable is a sticky-note label you put on a box, not the box itself — move the note, the box stays. 🏷️📦",
    key:"a name that points to an object" },
  { id:4, day:1, topic:"Python Foundations", type:"single", diff:"easy", time:30,
    q:"Which built-in function reveals an object's identity (address-like value)?",
    options:["addr()","id()","memory()","ref()"], answer:1,
    hint:"Like a car's chassis number that uniquely identifies it — this gives an object's unique identity. 🚗",
    key:"id()" },
  { id:5, day:1, topic:"Python Foundations", type:"multi", diff:"medium", time:50,
    q:"Which of the following are immutable in Python? (Select all that apply)",
    options:["list","tuple","string","dict"], answer:[1,2],
    hint:"A printed book (string) and a sealed gift box (tuple) can't be changed; a notepad (list) and a contacts app (dict) can. 📖🎁",
    key:"tuple and string are locked" },
  { id:6, day:1, topic:"Python Foundations", type:"single", diff:"easy", time:30,
    q:"Which collection is most useful for removing duplicate values?",
    options:["list","tuple","set","str"], answer:2,
    hint:"Like a guest list that automatically ignores repeated names — keeps only unique items. 📝",
    key:"set = unique only" },
  { id:7, day:1, topic:"Python Foundations", type:"single", diff:"easy", time:35,
    q:"PEP 8 is mainly about:",
    options:["Making code run faster","Code style and readability conventions","Encrypting code","Compiling to C"], answer:1,
    hint:"Like grammar and neat handwriting rules for an essay — it keeps code clean and readable. ✍️",
    key:"style / readability guide" },
  { id:8, day:1, topic:"Python Foundations", type:"multi", diff:"medium", time:50,
    q:"Which of these values are falsy in Python? (Select all that apply)",
    options:["0","\"\" (empty string)","[1]","\"0\""], answer:[0,1],
    hint:"Empty wallet (0) and empty bag ('') feel empty = falsy; a bag with one item [1] or the text '0' still counts. 👜",
    key:"zero and the empty string" },
  { id:9, day:1, topic:"Python Foundations", type:"single", diff:"easy", time:30,
    q:"What is the output of 7 // 2 ?", options:["3.5","3","4","1"], answer:1,
    hint:"Sharing 7 chocolates between 2 kids: each gets 3 whole ones (floor division ignores the leftover). 🍫",
    key:"floor division → 3" },
  { id:10, day:1, topic:"Python Foundations", type:"single", diff:"easy", time:35,
    q:"The main purpose of type hints in Python is to:",
    options:["Make code always run faster","Document expected types and improve readability/tooling","Replace variables","Prevent all runtime errors"], answer:1,
    hint:"Like labeling jars 'sugar' and 'salt' so nobody has to guess — they document expected types. 🏷️",
    key:"document expected types" },
  { id:11, day:1, topic:"Python Foundations", type:"tf", diff:"easy", time:20,
    q:"dis.dis() shows the internal bytecode instructions Python uses.", options:["True","False"], answer:0,
    hint:"Like X-raying a watch to see the gears turning inside — it reveals Python's bytecode. ⌚",
    key:"it shows bytecode" },

  // ---------------- Day 2: Functions, Files, Exceptions, OOP ----------------
  { id:12, day:2, topic:"Functions & OOP", type:"single", diff:"easy", time:30,
    q:"*args in a function definition is used to accept:",
    options:["Any number of positional arguments","Only one keyword argument","Only files","Only classes"], answer:0,
    hint:"Like a pizza that accepts any number of toppings — it takes any number of positional arguments. 🍕",
    key:"many positional arguments" },
  { id:13, day:2, topic:"Functions & OOP", type:"single", diff:"easy", time:30,
    q:"**kwargs in a function definition is used to accept:",
    options:["Any number of keyword arguments","Only integers","Only positional arguments","Only exceptions"], answer:0,
    hint:"Like a form with labeled fields you can add freely (name=, age=) — it takes named arguments. 📋",
    key:"many keyword arguments" },
  { id:14, day:2, topic:"Functions & OOP", type:"single", diff:"medium", time:40,
    q:"A decorator in Python usually:",
    options:["Wraps or modifies a function's behavior","Deletes a module","Creates a PDF","Runs SQL"], answer:0,
    hint:"Like gift-wrapping a present — it wraps a function to add behavior without changing the gift inside. 🎁",
    key:"wraps / extends a function" },
  { id:15, day:2, topic:"Functions & OOP", type:"single", diff:"easy", time:30,
    q:"Which keyword block is used to catch exceptions?",
    options:["try","except","raise","class"], answer:1,
    hint:"Like a safety net under a tightrope walker — it catches the fall (the error). 🎪",
    key:"except" },
  { id:16, day:2, topic:"Functions & OOP", type:"single", diff:"easy", time:35,
    q:"Why is 'with open(...)' commonly preferred for file handling?",
    options:["It trains a model","It closes the file automatically","It changes Python version","It removes all exceptions"], answer:1,
    hint:"Like a self-closing door — it auto-closes the file so you never forget. 🚪",
    key:"auto-closes the file" },
  { id:17, day:2, topic:"Functions & OOP", type:"tf", diff:"easy", time:20,
    q:"The finally block runs whether or not an exception occurs.", options:["True","False"], answer:0,
    hint:"Like always locking up the shop, whether the day was busy or quiet — finally always runs. 🔒",
    key:"it always runs" },
  { id:18, day:2, topic:"Functions & OOP", type:"single", diff:"easy", time:30,
    q:"The __init__ method of a class is commonly used to:",
    options:["Delete the class","Initialize object state","Catch errors","Sort a list"], answer:1,
    hint:"Like a factory setup line fitting each new car with its parts — it sets up a new object. 🏭",
    key:"initialize the object" },
  { id:19, day:2, topic:"Functions & OOP", type:"single", diff:"easy", time:30,
    q:"Inside a class method, 'self' usually refers to:",
    options:["The current object instance","The operating system","The parent folder","The compiler"], answer:0,
    hint:"Like the word 'me' — inside a method it means this particular object. 🙋",
    key:"this object instance" },
  { id:20, day:2, topic:"Functions & OOP", type:"single", diff:"medium", time:40,
    q:"Inheritance lets a class:",
    options:["Become a text file","Reuse and extend behavior from another class","Avoid all methods","Run without Python"], answer:1,
    hint:"Like a child inheriting traits from parents — a subclass reuses and extends the parent's behavior. 👨‍👦",
    key:"reuse and extend a parent" },
  { id:21, day:2, topic:"Functions & OOP", type:"single", diff:"easy", time:35,
    q:"Polymorphism allows:",
    options:["Different objects to respond to the same method name","Only one class in a program","Files to open automatically","Variables to be immutable"], answer:0,
    hint:"Press 'play' on a phone, TV, or car stereo — same button, each device responds its own way. ▶️",
    key:"same method name, many forms" },
  { id:22, day:2, topic:"Functions & OOP", type:"multi", diff:"medium", time:50,
    q:"Which of the following are core Object-Oriented Programming concepts? (Select all that apply)",
    options:["Encapsulation","Inheritance","Broadcasting","Polymorphism"], answer:[0,1,3],
    hint:"OOP's toolkit = wrapping (encapsulation), family traits (inheritance), many forms (polymorphism). Broadcasting is a NumPy thing! 🧰",
    key:"Encapsulation, Inheritance, Polymorphism" },

  // ---------------- Day 3: Statistics & Math for ML ----------------
  { id:23, day:3, topic:"Statistics for ML", type:"single", diff:"easy", time:30,
    q:"NumPy is especially useful for:",
    options:["Fast numerical array operations","Creating websites","Writing HTML forms","Replacing Python syntax"], answer:0,
    hint:"Like a calculator built for whole spreadsheets at once — it crunches arrays fast. 🧮",
    key:"fast array math" },
  { id:24, day:3, topic:"Statistics for ML", type:"single", diff:"easy", time:35,
    q:"Why do we use np.random.seed(42)?",
    options:["To make random results reproducible","To make code slower","To delete arrays","To create a class"], answer:0,
    hint:"Like shuffling cards the exact same way for a fair re-match — it makes randomness repeatable. 🎴",
    key:"reproducible randomness" },
  { id:25, day:3, topic:"Statistics for ML", type:"single", diff:"easy", time:30,
    q:"The mean of [2, 4, 6] is:", options:["2","4","6","12"], answer:1,
    hint:"Pool 2+4+6=12 sweets and split among 3 friends → 4 each. 🍬",
    key:"the average is 4" },
  { id:26, day:3, topic:"Statistics for ML", type:"single", diff:"easy", time:30,
    q:"Standard deviation measures:",
    options:["Spread/variation in data","Only the maximum","Only missing values","The number of columns"], answer:0,
    hint:"Two classes both average 60, but one ranges 55–65 and another 20–100 — this measures that spread. 📊",
    key:"the spread of the data" },
  { id:27, day:3, topic:"Statistics for ML", type:"single", diff:"easy", time:30,
    q:"A probability value must lie between:",
    options:["-1 and 1","0 and 1","1 and 100","Any two strings"], answer:1,
    hint:"Chance of rain runs 0% to 100% (0 to 1) — never 200%. 🌧️",
    key:"between 0 and 1" },
  { id:28, day:3, topic:"Hypothesis Testing", type:"single", diff:"medium", time:45,
    q:"In hypothesis testing, the null hypothesis (H0) usually states that:",
    options:["There is a strong effect","There is no effect or no difference","The data is wrong","The model is overfitting"], answer:1,
    hint:"A courtroom assumes 'innocent' (no effect) until evidence proves otherwise — that's the null hypothesis. ⚖️",
    key:"no effect / no difference" },
  { id:29, day:3, topic:"Hypothesis Testing", type:"single", diff:"medium", time:45,
    q:"A small p-value (for example p < 0.05) generally suggests that you should:",
    options:["Accept the null hypothesis","Reject the null hypothesis (result is statistically significant)","Ignore the result","Collect no more data"], answer:1,
    hint:"Strong, surprising evidence (a tiny p) makes you reject the 'nothing is going on' assumption. 🔍",
    key:"reject the null → significant" },
  { id:30, day:3, topic:"Hypothesis Testing", type:"tf", diff:"medium", time:30,
    q:"A p-value is the probability that the null hypothesis is true.", options:["True","False"], answer:1,
    hint:"Careful! A p-value is NOT 'the chance H0 is true' — it's how surprising your data is IF H0 were true. 🤔",
    key:"this is a common myth → False" },
  { id:31, day:3, topic:"Hypothesis Testing", type:"single", diff:"medium", time:45,
    q:"A t-test is commonly used to:",
    options:["Compare the means of groups","Reduce dimensions","Cluster data","Detect edges in images"], answer:0,
    hint:"Comparing the average heights of two teams to see if the difference is real — that's a t-test. 📏",
    key:"compare group means" },
  { id:32, day:3, topic:"A/B Testing", type:"single", diff:"medium", time:50,
    q:"In an A/B test comparing Model A vs Model B, 'statistical significance' tells us:",
    options:["Which model is newer","Whether the observed difference is likely real and not due to chance","Which model has more code","Which model is cheaper"], answer:1,
    hint:"Model B got more clicks — but is it real or just luck? Significance says it's probably real, not chance. 🎯",
    key:"the difference is real, not luck" },
  { id:33, day:3, topic:"Statistics for ML", type:"single", diff:"easy", time:35,
    q:"Correlation measures:",
    options:["Relationship between two variables","Only the average value","Only file size","Only runtime errors"], answer:0,
    hint:"Ice-cream sales and temperature rise together — correlation tracks how two things move. 🍦🌡️",
    key:"relationship between variables" },
  { id:34, day:3, topic:"Statistics for ML", type:"single", diff:"medium", time:45,
    q:"The Central Limit Theorem mainly describes the distribution of:",
    options:["Sample means","File names","Class methods","Pixels"], answer:0,
    hint:"Average many random samples and they form a tidy bell shape — that's the Central Limit Theorem. 🔔",
    key:"the distribution of sample means" },

  // ---------------- Day 4: NumPy & Pandas ----------------
  { id:35, day:4, topic:"NumPy & Pandas", type:"single", diff:"medium", time:45,
    q:"NumPy vectorized operations are faster than Python loops mainly because:",
    options:["They use slower interpreted steps","Operations run in optimized C over whole arrays","They skip the data","They use the GPU only"], answer:1,
    hint:"One photocopier copying a whole stack beats writing each page by hand — it runs in fast C. 🖨️",
    key:"optimized C over whole arrays" },
  { id:36, day:4, topic:"NumPy & Pandas", type:"single", diff:"medium", time:40,
    q:"What is the typical array shape of a single RGB image?",
    options:["(height, width)","(height, width, 3)","(3,)","(width,)"], answer:1,
    hint:"A color photo is a height × width grid, with each cell holding 3 numbers (Red, Green, Blue). 🖼️",
    key:"(height, width, 3)" },
  { id:37, day:4, topic:"NumPy & Pandas", type:"single", diff:"easy", time:35,
    q:"Broadcasting in NumPy lets you:",
    options:["Apply operations between compatible array shapes","Send files to GitHub","Convert Python into Java","Remove missing values"], answer:0,
    hint:"Give every student +5 bonus marks in a single stroke — it stretches shapes to apply ops. ➕",
    key:"stretch shapes to match" },
  { id:38, day:4, topic:"NumPy & Pandas", type:"single", diff:"easy", time:35,
    q:"Boolean masking is mainly used to:",
    options:["Filter array values using a condition","Create a slide","Rename a DataFrame","Train a model"], answer:0,
    hint:"A bouncer letting in only guests over 18 — a mask filters by a condition. 🚪",
    key:"filter by a condition" },
  { id:39, day:4, topic:"NumPy & Pandas", type:"single", diff:"easy", time:30,
    q:"In a grayscale image array, the value 0 usually represents:",
    options:["White","Black","Red","Transparent"], answer:1,
    hint:"In a black-and-white photo, 0 = pitch black and 255 = pure white. ⬛",
    key:"0 = black" },
  { id:40, day:4, topic:"NumPy & Pandas", type:"single", diff:"easy", time:30,
    q:"A Pandas DataFrame is:",
    options:["A table-like structure with rows and columns","A single number","An error message","A plotting style"], answer:0,
    hint:"Like an Excel sheet living inside Python — rows and columns. 📑",
    key:"a table of rows and columns" },
  { id:41, day:4, topic:"NumPy & Pandas", type:"single", diff:"easy", time:30,
    q:"Which Pandas method shows the first few rows of a DataFrame?",
    options:["head()","first_rows()","start()","preview()"], answer:0,
    hint:"Like peeking at the first page of a book — it shows the first rows. 📖",
    key:"head()" },
  { id:42, day:4, topic:"NumPy & Pandas", type:"single", diff:"easy", time:30,
    q:"Which Pandas method is commonly used to detect missing values?",
    options:["isna()","missing()","blank()","empty()"], answer:0,
    hint:"Like spotting blank answers on a test sheet — it finds the missing values. ❓",
    key:"isna()" },
  { id:43, day:4, topic:"NumPy & Pandas", type:"tf", diff:"easy", time:20,
    q:"groupby() in Pandas is used to aggregate data by category.", options:["True","False"], answer:0,
    hint:"Sorting receipts into piles by category to total each one — that's groupby. 🧾",
    key:"aggregate by category" },
  { id:44, day:4, topic:"NumPy & Pandas", type:"multi", diff:"medium", time:55,
    q:"Which of the following are valid data-cleaning steps? (Select all that apply)",
    options:["Handling missing values","Removing duplicate rows","Deleting all columns","Fixing wrong data types"], answer:[0,1,3],
    hint:"Cleaning a dataset = fill the blanks, toss duplicate entries, fix wrong types — but never delete EVERY column! 🧹",
    key:"missing, duplicates, wrong types" },
  { id:45, day:4, topic:"NumPy & Pandas", type:"single", diff:"medium", time:40,
    q:"Converting a cleaned DataFrame into a NumPy array is often done in order to:",
    options:["Feed it into ML models","Delete the data","Make a PDF","Open a browser"], answer:0,
    hint:"Convert your clean spreadsheet into pure numbers so the ML model can 'eat' it. 🍽️",
    key:"feed it to the model" },

  // ---------------- Day 5: Visualization & First ML Model ----------------
  { id:46, day:5, topic:"Visualization & ML", type:"single", diff:"easy", time:30,
    q:"Matplotlib is mainly used for:",
    options:["Creating plots and visualizations","Running SQL servers","Encrypting files","Creating GitHub orgs"], answer:0,
    hint:"Your go-to drawing app for charts in Python. 📈",
    key:"plots and charts" },
  { id:47, day:5, topic:"Visualization & ML", type:"single", diff:"easy", time:30,
    q:"Seaborn is built on top of which library?",
    options:["Matplotlib","Git","Excel","Google Forms"], answer:0,
    hint:"Seaborn is the stylish jacket worn over Matplotlib. 🧥",
    key:"Matplotlib" },
  { id:48, day:5, topic:"Visualization & ML", type:"single", diff:"easy", time:30,
    q:"A histogram helps you understand:",
    options:["The distribution of a numeric variable","A student's username","Number of Git commits","Function syntax"], answer:0,
    hint:"Like sorting exam scores into bins (0–10, 10–20…) to see the shape of the class. 📊",
    key:"the distribution of values" },
  { id:49, day:5, topic:"Visualization & ML", type:"single", diff:"easy", time:35,
    q:"A boxplot is especially useful for spotting:",
    options:["Outliers and spread","File names","Imports","Passwords"], answer:0,
    hint:"It instantly spots the one student who scored wildly different — an outlier. 📦",
    key:"outliers and spread" },
  { id:50, day:5, topic:"Visualization & ML", type:"single", diff:"medium", time:40,
    q:"A correlation heatmap is used to show:",
    options:["Correlation between numeric columns","The model's file size","The Python version","The number of rows only"], answer:0,
    hint:"A color grid showing which features move together — bright red = strong link. 🔥",
    key:"correlation between columns" },
  { id:51, day:5, topic:"Visualization & ML", type:"single", diff:"medium", time:45,
    q:"In supervised learning, X and y usually represent:",
    options:["X = target vector, y = features","X = feature matrix, y = target vector","Both are the same","Two unrelated files"], answer:1,
    hint:"X = the clues (features), y = the answer you want to predict (target). 🕵️",
    key:"X = features, y = target" },
  { id:52, day:5, topic:"Visualization & ML", type:"single", diff:"easy", time:35,
    q:"train_test_split is used to:",
    options:["Split data into training and testing sets","Delete the dataset","Draw a histogram","Open a CSV"], answer:0,
    hint:"Study with most of your flashcards, then quiz yourself on the rest — that's the train/test split. 🃏",
    key:"split into train and test" },
  { id:53, day:5, topic:"Visualization & ML", type:"single", diff:"easy", time:30,
    q:"In scikit-learn, model.fit(X_train, y_train) is used to:",
    options:["Train the model","Draw a chart","Open a file","Count missing values"], answer:0,
    hint:"fit() is the 'study' step where the model actually learns. 📚",
    key:"it trains the model" },
  { id:54, day:5, topic:"Visualization & ML", type:"single", diff:"medium", time:45,
    q:"R-squared (R²) is commonly interpreted as:",
    options:["How much variance the model explains","The model's file size","The number of missing values","The Python version"], answer:0,
    hint:"R² = how much of the story your model explains (1.0 means it explains the whole story). 📖",
    key:"variance the model explains" },
  { id:55, day:5, topic:"Visualization & ML", type:"single", diff:"easy", time:35,
    q:"For a regression model, a lower MSE usually means:",
    options:["Predictions are closer to actual values","The model is more random","More strings in data","No functions used"], answer:0,
    hint:"Darts landing near the bullseye = low error = good. 🎯",
    key:"predictions are closer" },
  { id:56, day:5, topic:"Visualization & ML", type:"tf", diff:"easy", time:25,
    q:"The test set should be used only for final evaluation, not for training.", options:["True","False"], answer:0,
    hint:"Don't peek at the final exam while studying — the test set is for the final check only. 🙈",
    key:"final evaluation only" },

  // ---------------- Day 6: Classification ----------------
  { id:57, day:6, topic:"Classification", type:"single", diff:"easy", time:30,
    q:"The sigmoid function maps any real number into the range:",
    options:["0 to 1","-100 to 100","Only integers","2 to 10"], answer:0,
    hint:"It squishes any number into a 0–1 'probability squeeze'. 🤏",
    key:"0 to 1" },
  { id:58, day:6, topic:"Classification", type:"single", diff:"medium", time:40,
    q:"For the sigmoid function, an input of z = 0 gives an output of:",
    options:["0","0.5","1","-1"], answer:1,
    hint:"At the exact middle (z = 0) it's a coin-flip → 0.5. 🪙",
    key:"0.5" },
  { id:59, day:6, topic:"Classification", type:"single", diff:"easy", time:30,
    q:"Logistic Regression is mainly used for:",
    options:["Classification","Compressing files","Sorting images","Creating slides"], answer:0,
    hint:"Spam or not spam? Yes/No questions = classification. 📧",
    key:"classification" },
  { id:60, day:6, topic:"Classification", type:"single", diff:"easy", time:35,
    q:"In binary classification, a threshold such as 0.5 is used to:",
    options:["Convert a probability into a class decision","Convert rows into columns","Remove plots","Create random labels"], answer:0,
    hint:"Pass if score ≥ 50% — a threshold turns a probability into a yes/no decision. ✅",
    key:"probability → decision" },
  { id:61, day:6, topic:"Classification", type:"single", diff:"easy", time:35,
    q:"A confusion matrix shows:",
    options:["Correct and incorrect predictions by class","Only model coefficients","Only missing values","Only feature names"], answer:0,
    hint:"A scorecard of right vs wrong predictions, broken down per class. 🗂️",
    key:"right vs wrong per class" },
  { id:62, day:6, topic:"Classification", type:"single", diff:"medium", time:50,
    q:"Precision answers which question?",
    options:["Of the items predicted positive, how many are truly positive?","Of the actual positives, how many did we find?","What is the average error?","How deep is the tree?"], answer:0,
    hint:"Of all the emails you FLAGGED as spam, how many really were spam? That's precision. 🎯",
    key:"of predicted-positive, how many correct" },
  { id:63, day:6, topic:"Classification", type:"single", diff:"medium", time:50,
    q:"Recall answers which question?",
    options:["Of the actual positives, how many were correctly found?","Of predicted positives, how many are correct?","What is the variance explained?","How many neighbors are used?"], answer:0,
    hint:"Of ALL the real spam out there, how much did you actually catch? That's recall. 🕸️",
    key:"of actual-positive, how many found" },
  { id:64, day:6, topic:"Classification", type:"single", diff:"medium", time:40,
    q:"The F1-score is:",
    options:["The harmonic mean of precision and recall","The sum of all errors","The model's accuracy on training only","The number of features"], answer:0,
    hint:"The fair 'balance' score that combines precision and recall. ⚖️",
    key:"harmonic mean of P and R" },
  { id:65, day:6, topic:"Classification", type:"single", diff:"easy", time:30,
    q:"In KNN, the value K represents:",
    options:["The number of neighbors considered","The number of columns deleted","The learning rate","The chart size"], answer:0,
    hint:"Ask your K nearest neighbors for advice — K is how many you ask. 🏘️",
    key:"number of neighbors" },
  { id:66, day:6, topic:"Classification", type:"single", diff:"easy", time:35,
    q:"KNN makes a prediction by:",
    options:["Looking at nearby training examples","Learning a single coefficient","Ignoring distance","Always choosing the first row"], answer:0,
    hint:"You're judged by the company you keep — KNN looks at the nearest points. 👥",
    key:"looks at nearby examples" },
  { id:67, day:6, topic:"Classification", type:"multi", diff:"medium", time:50,
    q:"Which of the following are classification evaluation metrics? (Select all that apply)",
    options:["Precision","Recall","MSE","F1-score"], answer:[0,1,3],
    hint:"Precision, Recall and F1 grade classifiers; MSE grades regression. 🧮",
    key:"Precision, Recall, F1-score" },

  // ---------------- Day 7: Decision Trees & Random Forests ----------------
  { id:68, day:7, topic:"Trees & Forests", type:"single", diff:"easy", time:35,
    q:"A decision tree makes a prediction by:",
    options:["Following a series of yes/no splits","Only computing distance","Always using sigmoid","Drawing charts"], answer:0,
    hint:"A flowchart of yes/no questions leading to an answer — like the game 'Akinator'. 🌳",
    key:"a series of yes/no splits" },
  { id:69, day:7, topic:"Trees & Forests", type:"single", diff:"easy", time:35,
    q:"The max_depth parameter of a decision tree controls:",
    options:["How deep the tree can grow","How many CSV files are read","How many plots appear","How many labels exist"], answer:0,
    hint:"How many yes/no levels deep the tree is allowed to go. 📏",
    key:"the tree's depth limit" },
  { id:70, day:7, topic:"Trees & Forests", type:"single", diff:"medium", time:45,
    q:"An unconstrained (very deep) decision tree tends to:",
    options:["Overfit the training data","Always underfit","Ignore the features","Run forever"], answer:0,
    hint:"A student who memorizes the textbook word-for-word but fails new questions — that's overfitting. 🤓",
    key:"overfit the training data" },
  { id:71, day:7, topic:"Trees & Forests", type:"single", diff:"easy", time:35,
    q:"A Random Forest improves stability by:",
    options:["Combining predictions from many trees","Using only one split","Removing all features","Skipping train/test split"], answer:0,
    hint:"Ask a whole crowd of trees and let them vote — far more stable than just one. 🌲🌲🌲",
    key:"combining many trees" },
  { id:72, day:7, topic:"Trees & Forests", type:"single", diff:"medium", time:45,
    q:"Ensemble methods such as Random Forests mainly help to reduce:",
    options:["Variance / overfitting","The dataset size","The number of features","The Python version"], answer:0,
    hint:"A panel of judges averages out any one judge's bias — ensembles cut variance. 👨‍⚖️",
    key:"variance / overfitting" },
  { id:73, day:7, topic:"Trees & Forests", type:"single", diff:"easy", time:40,
    q:"Feature importance tells us:",
    options:["Which features helped the model split/predict","Which column must be deleted","Which model is always perfect","Which file to open"], answer:0,
    hint:"Which clues mattered most for the verdict? That's feature importance. 🔑",
    key:"which features mattered most" },
  { id:74, day:7, topic:"Trees & Forests", type:"tf", diff:"easy", time:25,
    q:"A deeper decision tree always generalizes better to new data.", options:["True","False"], answer:1,
    hint:"Memorizing more trivia doesn't make you wiser on brand-new problems. ❌",
    key:"deeper isn't always better → False" },
  { id:75, day:7, topic:"Trees & Forests", type:"single", diff:"medium", time:40,
    q:"Random Forest is an example of:",
    options:["An ensemble method","A clustering method","A dimensionality reduction method","An activation function"], answer:0,
    hint:"A team of trees working together = an ensemble. 🌳🤝",
    key:"an ensemble method" },
  { id:76, day:7, topic:"Trees & Forests", type:"tf", diff:"medium", time:30,
    q:"Decision trees are considered relatively interpretable models.", options:["True","False"], answer:0,
    hint:"You can literally read a tree's path like a recipe — that's interpretable. 📜",
    key:"yes, they're interpretable → True" },
  { id:77, day:7, topic:"Trees & Forests", type:"single", diff:"easy", time:35,
    q:"Each split in a decision tree is based on:",
    options:["A condition on a feature","A random color","The file name","The Python version"], answer:0,
    hint:"Each fork asks a question about one feature, e.g. 'age > 30?'. 🍴",
    key:"a condition on a feature" },
  { id:78, day:7, topic:"Trees & Forests", type:"multi", diff:"medium", time:55,
    q:"Which of the following help reduce overfitting in tree-based models? (Select all that apply)",
    options:["Limiting max_depth","Using a Random Forest","Growing the tree infinitely deep","Pruning the tree"], answer:[0,1,3],
    hint:"Tame a wild tree: cap its depth, prune it, or use a forest — never grow it forever! ✂️🌲",
    key:"limit depth, use forest, prune" },

  // ---------------- Day 8: Naive Bayes, SVM, K-Means, PCA ----------------
  { id:79, day:8, topic:"NB / SVM / Clustering", type:"single", diff:"easy", time:35,
    q:"Naive Bayes is commonly used for:",
    options:["Text classification","Edge detection","Image cropping","Sorting files"], answer:0,
    hint:"A lightning-fast spam filter built from word counts — classic Naive Bayes. ⚡📧",
    key:"text classification" },
  { id:80, day:8, topic:"NB / SVM / Clustering", type:"single", diff:"medium", time:45,
    q:"CountVectorizer / Bag-of-Words converts text into:",
    options:["A numerical table of word counts","A single image","A decision tree","An audio file"], answer:0,
    hint:"Counting how many times each word appears — a word-frequency tally. 🔢",
    key:"a table of word counts" },
  { id:81, day:8, topic:"NB / SVM / Clustering", type:"single", diff:"easy", time:35,
    q:"A Support Vector Machine (SVM) tries to find:",
    options:["A boundary that separates classes","The mean of the data","The number of files","The Python version"], answer:0,
    hint:"Drawing the widest possible 'street' that separates two neighborhoods. 🛣️",
    key:"a boundary between classes" },
  { id:82, day:8, topic:"NB / SVM / Clustering", type:"single", diff:"medium", time:45,
    q:"The RBF kernel allows an SVM to create:",
    options:["Curved / nonlinear decision boundaries","Only straight lines","Histograms","Random labels"], answer:0,
    hint:"When a straight fence won't separate the yards, RBF bends it into curves. 〰️",
    key:"curved / nonlinear boundaries" },
  { id:83, day:8, topic:"NB / SVM / Clustering", type:"single", diff:"easy", time:35,
    q:"K-Means clustering is an example of which type of learning?",
    options:["Unsupervised learning","Supervised learning","Reinforcement learning","Manual learning"], answer:0,
    hint:"Sorting a mixed bag of marbles by color when no labels were given. 🔵🔴",
    key:"unsupervised learning" },
  { id:84, day:8, topic:"NB / SVM / Clustering", type:"single", diff:"easy", time:35,
    q:"K-Means groups data by:",
    options:["Similarity into clusters","Alphabetical order","File size","Creation date"], answer:0,
    hint:"Birds of a feather flock together — it clusters by similarity. 🐦",
    key:"similarity into clusters" },
  { id:85, day:8, topic:"NB / SVM / Clustering", type:"single", diff:"medium", time:45,
    q:"The Elbow Method helps you choose:",
    options:["The number of clusters K","The learning rate","The tree depth","The image size"], answer:0,
    hint:"The 'bend' in the graph (like an elbow) reveals the sweet-spot number of groups. 💪",
    key:"the number of clusters K" },
  { id:86, day:8, topic:"PCA", type:"single", diff:"easy", time:35,
    q:"PCA (Principal Component Analysis) is mainly used for:",
    options:["Dimensionality reduction","Image cropping","Text tokenization","File compression only"], answer:0,
    hint:"Squeezing a fat report into a crisp summary while keeping the gist — fewer dimensions. 🗜️",
    key:"dimensionality reduction" },
  { id:87, day:8, topic:"PCA", type:"single", diff:"medium", time:50,
    q:"In PCA, the principal components are:",
    options:["New axes that capture the most variance in the data","The original columns unchanged","Random noise","The labels"], answer:0,
    hint:"New 'best-view' camera angles that capture the most action (variance). 🎥",
    key:"new axes of maximum variance" },
  { id:88, day:8, topic:"PCA", type:"single", diff:"medium", time:50,
    q:"The explained variance ratio in PCA tells us:",
    options:["How much information (variance) each component retains","How many rows exist","The file size","The model accuracy"], answer:0,
    hint:"What percentage of the original story each summary line keeps. 📊",
    key:"info retained per component" },
  { id:89, day:8, topic:"PCA", type:"tf", diff:"medium", time:30,
    q:"PCA reduces the number of dimensions while trying to keep most of the variance.", options:["True","False"], answer:0,
    hint:"Shrink the photo but keep it recognizable — PCA keeps most of the variance. 🖼️",
    key:"yes, keeps the variance → True" },
  { id:90, day:8, topic:"NB / SVM / Clustering", type:"single", diff:"medium", time:45,
    q:"The Silhouette Score is used to measure:",
    options:["How well-separated and tight the clusters are","The training accuracy","The number of features","The learning rate"], answer:0,
    hint:"Are the cliques tight inside and far apart from each other? Silhouette scores that. 👥↔️👥",
    key:"how good the clusters are" },

  // ---------------- Day 9: Deep Learning ----------------
  { id:91, day:9, topic:"Deep Learning", type:"single", diff:"medium", time:45,
    q:"A single artificial neuron computes:",
    options:["A weighted sum plus bias, followed by an activation","Only a random number","The median of inputs","A file path"], answer:0,
    hint:"Mix the ingredients with weights, add a pinch (bias), then taste-decide (activation). 👩‍🍳",
    key:"weighted sum + bias + activation" },
  { id:92, day:9, topic:"Deep Learning", type:"single", diff:"medium", time:45,
    q:"The ReLU activation function outputs:",
    options:["0 for negative inputs and the value itself for positive inputs","Always 1","Always 0","A value between -1 and 1"], answer:0,
    hint:"A one-way valve: it blocks negatives (→0) and lets positives flow through. 🚰",
    key:"0 for negatives, x for positives" },
  { id:93, day:9, topic:"Deep Learning", type:"single", diff:"easy", time:40,
    q:"Gradient descent is used to:",
    options:["Minimize the loss by updating the weights","Open a file","Draw a chart","Tokenize text"], answer:0,
    hint:"Walking downhill in fog, step by step, to reach the lowest valley (least error). ⛰️",
    key:"minimize the loss" },
  { id:94, day:9, topic:"Deep Learning", type:"single", diff:"medium", time:45,
    q:"The learning rate controls:",
    options:["The step size of weight updates","The number of layers","The image size","The dataset size"], answer:0,
    hint:"Big steps are fast but may overshoot; tiny steps are safe but slow. 👣",
    key:"the step size" },
  { id:95, day:9, topic:"Deep Learning", type:"single", diff:"medium", time:45,
    q:"A learning rate that is set too high can cause training to:",
    options:["Diverge or overshoot the minimum","Always be perfect","Stop using GPUs","Delete the data"], answer:0,
    hint:"Leaping too far downhill and bouncing right past the valley — it diverges. 🦘",
    key:"overshoot / diverge" },
  { id:96, day:9, topic:"Deep Learning", type:"single", diff:"easy", time:35,
    q:"A Keras Dense layer is:",
    options:["A fully connected layer","An image file","A loss function","A CSV reader"], answer:0,
    hint:"Every neuron shakes hands with every neuron in the next layer. 🤝",
    key:"a fully connected layer" },
  { id:97, day:9, topic:"Deep Learning", type:"single", diff:"medium", time:45,
    q:"For binary classification, the output layer of a neural network often uses which activation?",
    options:["Sigmoid","ReLU","None","Linear only"], answer:0,
    hint:"A Yes/No output → squeeze it to a 0–1 probability with sigmoid. 🤏",
    key:"sigmoid" },
  { id:98, day:9, topic:"Deep Learning", type:"single", diff:"easy", time:35,
    q:"The optimizer's job during training is to:",
    options:["Update the weights to reduce the loss","Load images","Print the model","Split the data"], answer:0,
    hint:"The coach who adjusts the team (weights) after each game to lose less often. 🏟️",
    key:"update weights to cut loss" },
  { id:99, day:9, topic:"Deep Learning", type:"single", diff:"medium", time:50,
    q:"If the training loss keeps dropping but the validation loss starts rising, the model is likely:",
    options:["Overfitting","Underfitting","Perfectly trained","Out of data"], answer:0,
    hint:"Acing the practice papers but flunking the real test = overfitting. 📉",
    key:"overfitting" },
  { id:100, day:9, topic:"Deep Learning", type:"tf", diff:"easy", time:25,
    q:"A loss function measures how wrong the model's predictions are.", options:["True","False"], answer:0,
    hint:"A 'wrongness meter' — the higher it reads, the worse the predictions. 🌡️",
    key:"it measures error → True" },
  { id:101, day:9, topic:"Deep Learning", type:"multi", diff:"medium", time:55,
    q:"Which of the following are activation functions? (Select all that apply)",
    options:["ReLU","Sigmoid","Adam","Softmax"], answer:[0,1,3],
    hint:"ReLU, Sigmoid and Softmax shape the signal; Adam is an optimizer, not an activation. ⚡",
    key:"ReLU, Sigmoid, Softmax" },

  // ---------------- Day 10: Computer Vision & CNNs ----------------
  { id:102, day:10, topic:"Computer Vision", type:"single", diff:"easy", time:30,
    q:"On a computer, images are stored as:",
    options:["Arrays of pixel values","Plain text only","Audio signals","SQL tables"], answer:0,
    hint:"Zoom far enough into any photo and it's just a grid of numbers (pixels). 🔢🖼️",
    key:"arrays of pixels" },
  { id:103, day:10, topic:"Computer Vision", type:"single", diff:"medium", time:40,
    q:"By default, OpenCV loads color images in which channel order?",
    options:["BGR","RGB","CMYK","Grayscale only"], answer:0,
    hint:"OpenCV is quirky — it reads colors as Blue-Green-Red, not the usual RGB. 🔵🟢🔴",
    key:"BGR" },
  { id:104, day:10, topic:"Computer Vision", type:"single", diff:"easy", time:35,
    q:"Grayscale conversion of an image:",
    options:["Reduces it to a single intensity channel","Adds more colors","Doubles the resolution","Encrypts the image"], answer:0,
    hint:"Strip away the color and keep only the brightness — one channel. 🌫️",
    key:"single intensity channel" },
  { id:105, day:10, topic:"Computer Vision", type:"single", diff:"easy", time:35,
    q:"Blurring an image is mainly used to:",
    options:["Remove noise / smooth the image","Add sharp edges","Increase file size only","Rotate the image"], answer:0,
    hint:"Softening a photo to hide grain and noise. 😌",
    key:"remove noise / smooth" },
  { id:106, day:10, topic:"Computer Vision", type:"single", diff:"medium", time:45,
    q:"A kernel (filter) in image processing is used to:",
    options:["Apply effects such as edge detection or sharpening","Open a CSV","Train an LSTM","Tokenize text"], answer:0,
    hint:"A tiny stencil slid across the image to detect edges or sharpen it. 🔲",
    key:"a filter for image effects" },
  { id:107, day:10, topic:"Computer Vision", type:"single", diff:"easy", time:35,
    q:"Thresholding an image is used to:",
    options:["Separate foreground from background","Add color","Increase brightness only","Rotate the image"], answer:0,
    hint:"Turn a photo into pure black-or-white to split the object from its background. ⚫⚪",
    key:"foreground vs background" },
  { id:108, day:10, topic:"Computer Vision", type:"single", diff:"easy", time:35,
    q:"Contours in computer vision are used to:",
    options:["Detect object boundaries / shapes","Compress files","Tokenize words","Split datasets"], answer:0,
    hint:"Tracing the outline around a shape, like cookie-cutter edges. 🍪",
    key:"detect object boundaries" },
  { id:109, day:10, topic:"Computer Vision", type:"single", diff:"medium", time:40,
    q:"A bounding box is used to:",
    options:["Locate / crop a region of interest","Blur the whole image","Convert text to numbers","Train a tree"], answer:0,
    hint:"The green rectangle a face-detector draws around your face. 🟩",
    key:"locate / crop a region" },
  { id:110, day:10, topic:"Computer Vision", type:"single", diff:"medium", time:45,
    q:"Convolutional Neural Networks (CNNs) are especially good at:",
    options:["Learning spatial patterns in images","Sorting text alphabetically","Reading CSV files","Compressing audio"], answer:0,
    hint:"CNNs have an 'eye' for patterns, edges and textures in images. 👁️",
    key:"spatial patterns in images" },
  { id:111, day:10, topic:"Computer Vision", type:"tf", diff:"easy", time:30,
    q:"cv2.imshow() can crash Google Colab, so we display images with Matplotlib instead.", options:["True","False"], answer:0,
    hint:"imshow() wants a desktop window that Colab's server doesn't have — so we use plt. 🖥️❌",
    key:"True" },
  { id:112, day:10, topic:"Computer Vision", type:"single", diff:"medium", time:45,
    q:"The convolutional layers in a CNN learn:",
    options:["Filters / features automatically from the data","The file names","The dataset size","The Python version"], answer:0,
    hint:"The filters aren't hand-drawn — the CNN learns them itself from the data. 🤖",
    key:"filters learned automatically" },

  // ---------------- Day 11: NLP & LSTMs ----------------
  { id:113, day:11, topic:"NLP & LSTM", type:"single", diff:"easy", time:35,
    q:"Tokenization converts:",
    options:["Words into integer IDs","Images into audio","Numbers into text","Files into folders"], answer:0,
    hint:"Give each word a jersey number so the network can handle it. 🔢👕",
    key:"words → integer IDs" },
  { id:114, day:11, topic:"NLP & LSTM", type:"single", diff:"easy", time:35,
    q:"Padding in NLP is used to:",
    options:["Make sequences the same length","Delete words","Add color to text","Encrypt the text"], answer:0,
    hint:"Add blank seats so every row (sentence) is the same length. 🪑",
    key:"equal-length sequences" },
  { id:115, day:11, topic:"NLP & LSTM", type:"single", diff:"medium", time:40,
    q:"An Embedding layer converts words into:",
    options:["Dense numeric vectors","Images","Audio clips","Decision trees"], answer:0,
    hint:"Turn words into coordinates where 'king' and 'queen' sit close together. 🗺️",
    key:"words → dense vectors" },
  { id:116, day:11, topic:"NLP & LSTM", type:"single", diff:"medium", time:45,
    q:"An LSTM is specially designed to process:",
    options:["Sequential / ordered data over time","Single static numbers","Only images","Only CSV tables"], answer:0,
    hint:"Reads text in order and remembers earlier words — like following a story. 📖",
    key:"sequential / ordered data" },
  { id:117, day:11, topic:"NLP & LSTM", type:"single", diff:"easy", time:35,
    q:"The special token <OOV> represents:",
    options:["Unseen / out-of-vocabulary words","The end of a file","A padding zero","A correct answer"], answer:0,
    hint:"A 'stranger' tag for any word the model never saw during training. 🕵️",
    key:"unseen words" },
  { id:118, day:11, topic:"NLP & LSTM", type:"tf", diff:"easy", time:25,
    q:"Raw text can be fed directly into a neural network without any processing.", options:["True","False"], answer:1,
    hint:"A network speaks numbers, not raw letters — text must be processed first. 🔢",
    key:"text needs processing → False" },
  { id:119, day:11, topic:"NLP & LSTM", type:"single", diff:"medium", time:50,
    q:"True text summarization (generating new sentences) typically requires:",
    options:["An encoder-decoder architecture","A single Dense layer","Only tokenization","A decision tree"], answer:0,
    hint:"One part 'reads & understands', another part 'writes' the summary — encoder-decoder. 📥📤",
    key:"encoder-decoder architecture" },
  { id:120, day:11, topic:"NLP & LSTM", type:"single", diff:"medium", time:45,
    q:"Using stratify=labels in train_test_split is meant to:",
    options:["Keep the class balance in both splits","Shuffle the columns","Delete rare classes","Increase the dataset size"], answer:0,
    hint:"Keep the same ratio of each class in both groups when splitting. ⚖️",
    key:"keep class balance" }
];

if (typeof module !== "undefined") { module.exports = QUESTIONS; }
